version: '3.8'

volumes:
  pgdata: {}

services:
  db:
    image: postgres:14
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    networks:
      - lisek
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
      labels:
        - db
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lisek
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
      labels:
        - redis
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "localhost",
          "-p",
          "6379",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "BUILD_ENV=production"
    volumes:
      - ./config.docker.yml:/app/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data:rw
      - ./preloaded:/app/preloaded:rw
    environment:
      # Put your directory here
      - DATA_DIR=/home/dhcpcd9/Work/lisek-api/data/
      - PRELOADED_DIR=/home/dhcpcd9/Work/lisek-api/preloaded/
    ports:
      - "8080:8080"
    networks:
      - lisek
    depends_on:
      - redis
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
  velocity:
    image: itzg/bungeecord:java11
    environment:
      - TYPE=VELOCITY
      - PLUGINS=https://github.com/Lisek-World-Reborn/LisekVelocity/releases/download/v1.1/base.jar
      - SPIGET_PLUGINS=2124
      - ENABLE_RCON=true
      - RCON_PASSWORD=123456
      - RCON_PORT=25575
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_HOST=web
      - API_PORT=8080
      - API_TOKEN=secret
    ports:
      - "25577:25577"
    volumes:
      - ./data/bungee:/server:rw
    networks:
      - lisek
    depends_on:
      - web
networks:
  lisek:
    driver: bridge